6/8/26. Trying to split the sample based on eye state AND self-report. Previous notebook only did eye state.  

6/12/26. revising everythign to use mackenzie's csv.

In [91]:
import pandas as pd

# This is the base df. It is the fully processed, official INET runs list. However, some runs are missing from it, 
# so I add them back in manually later on.
df = pd.read_csv(r"C:\Users\tempu\Downloads\research\labs\gratton\Arousal-Project\splitting_sample\full_sample.csv")

df.head(3)

,sub,ses,task,run,filename,number_of_TRs,abnormal_TR,error_run,note,sleepiness__1_7_scale_,...,confidence,alignment,tmask_filepath,tmask_filename,num_tps_retained,percent_tps_retained,fFD_filepath,fFD_filename,mean_fFD,max_fFD
0,sub-INET001,ses-1,task-rest,run-01,sub-INET001_ses-1_task-rest_run-01_bold.nii.gz,270,0,NaN,NaN,1.0,...,NaN,include,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-01_desc-tmask_...,263,97.407407,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-01_desc-fFD.txt,0.026217,0.166371
1,sub-INET001,ses-1,task-rest,run-02,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,270,0,NaN,NaN,1.0,...,NaN,include,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-02_desc-tmask_...,265,98.148148,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-02_desc-fFD.txt,0.024525,0.084208
2,sub-INET001,ses-1,task-rest,run-03,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,270,0,NaN,NaN,1.0,...,NaN,include,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-03_desc-tmask_...,265,98.148148,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-03_desc-fFD.txt,0.024502,0.093614

In [92]:

print("**Dimensions of base df:** "), print(df.shape), 
print("\n**Columns:**"), print(df.columns),
print("\n**Number of subjects:**"), print(len(df["sub"].unique())),
print("\n**Notes:**"), print(df["note"].unique())

**Dimensions of base df:**
(2474, 22)

**Columns:**
Index(['sub', 'ses', 'task', 'run', 'filename', 'number_of_TRs', 'abnormal_TR',
       'error_run', 'note', 'sleepiness__1_7_scale_', 'alertness', 'focus',
       'confidence', 'alignment', 'tmask_filepath', 'tmask_filename',
       'num_tps_retained', 'percent_tps_retained', 'fFD_filepath',
       'fFD_filename', 'mean_fFD', 'max_fFD'],
      dtype='str')

**Number of subjects:**
94

**Notes:**
<StringArray>
[                                                    nan,
                                    'done after MRA/MRV',
                                      'big spike at end',
                                           'long blinks',
                     '1st time stopped early, restarted',
                                           'slow blinks',
                                      'HIRMM 81% <.1 mm',
                     '1st 30 sec have a lot of movement',
                            'really great, surprisingly',
                                        'had to restart',
                                                  'mask',
                                         'new field map',
                                           'field map 1',
                                           'field map 2',
                                            'fieldmap 1',
                                            'fieldmap 2',
           'stopped in middle, got dizzy, squeezed ball',
                                     'super long blinks',
                        'long blinks in last 90 seconds',
                            'long blinks in second half',
                            'long blinks in last minute',
            'long blinks; especially in the last minute',
                               'long blinks in 2nd half',
                                      'lots of movement',
                                   'head moved location',
                                        'lots of motion',
                                         'pulse stopped',
                                           'high motion',
                                 'motion in second half',
                                                'motion',
                                     'resp belt stopped',
                 'long blinks, respiratory belt stopped',
                                'long blinks first half',
                                'Long blinks throughout',
                                           'Long blinks',
               'longer blinks, respiration belt stopped',
 'had to restart --> 2nd scout and fieldmap starts here',
                    're-ran field map (had to take out)',
                                'long blinks throughout',
                           'long blinks in the 2nd half',
                             'resp belt stopped working',
                                       'new filedmap!!!',
                           'new fieldmap starts here !!',
                                     'high motion start',
                           'resp belt stopped recording',
                                   'lots of long blinks',
     '(power went to generator--> scanner kept running)',
                                       'long eye blinks',
                                      'eyes/long blinks',
       '*was 20 minutes late--> make up extra rest runs']
Length: 50, dtype: str

(None, None)

In [93]:
# Need to re-make eyes_closed category

eyes_closed_notes = ['long blinks', 'slow blinks', 'super long blinks', 
       'long blinks in last 90 seconds',
       'long blinks in second half',
       'long blinks; especially in the last minute',
       'long blinks in 2nd half',
       'long blinks, respiratory belt stopped',
       'long blinks first half', 'Long blinks throughout', 'Long blinks',
       'longer blinks, respiration belt stopped',
       'long blinks throughout',
       'long blinks in the 2nd half',
       'lots of long blinks',
       'long eye blinks', 'eyes/long blinks',
       ]

import numpy as np

# If the note is indicative of eyes_closed, we put them in the low arousal group.
for i in range(len(df)):
    if df.loc[i, "note"] in eyes_closed_notes:
        df.loc[i, "category"] = "eyes_closed"
    else:
        df.loc[i, "category"] = "eyes_opened"

# Rename to match the original, partial csv.
df.rename(columns = {"sleepiness__1_7_scale_" : "sleep-score", "percent_tps_retained" : "FD-hold"}, inplace = True)

# Make FD-hold < 1.
df["FD-hold"] = df["FD-hold"] * .01

# Drop unnecessary variables to avoid confusion and unnecessary complexity.
df.drop(columns = ["note", "error_run", "abnormal_TR", "alertness", "focus", "confidence", "alignment", "mean_fFD", "max_fFD"], inplace = True)

# Check how many eyes_closed runs there are.
len(df[df["category"] == "eyes_closed"])

34

In [94]:
# What does it look like?
df.head(5)

,sub,ses,task,run,filename,number_of_TRs,sleep-score,tmask_filepath,tmask_filename,num_tps_retained,FD-hold,fFD_filepath,fFD_filename,category
0,sub-INET001,ses-1,task-rest,run-01,sub-INET001_ses-1_task-rest_run-01_bold.nii.gz,270,1.0,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-01_desc-tmask_...,263,0.974074,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-01_desc-fFD.txt,eyes_opened
1,sub-INET001,ses-1,task-rest,run-02,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,270,1.0,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-02_desc-tmask_...,265,0.981481,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-02_desc-fFD.txt,eyes_opened
2,sub-INET001,ses-1,task-rest,run-03,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,270,1.0,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-03_desc-tmask_...,265,0.981481,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-03_desc-fFD.txt,eyes_opened
3,sub-INET001,ses-1,task-rest,run-04,sub-INET001_ses-1_task-rest_run-04_bold.nii.gz,270,1.0,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-04_desc-tmask_...,265,0.981481,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-04_desc-fFD.txt,eyes_opened
4,sub-INET001,ses-1,task-rest,run-05,sub-INET001_ses-1_task-rest_run-05_bold.nii.gz,270,1.0,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-05_desc-tmask_...,265,0.981481,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET001_ses-1_task-rest_run-05_desc-fFD.txt,eyes_opened

In [95]:
### We need to add the rest of the eyes_closed runs.
 
# This df accurately notes the eyes_closed runs.
df_merge = pd.read_csv(r"C:\Users\tempu\Downloads\research\labs\gratton\Arousal-Project\splitting_sample\larger_sample\larger_sample.csv")

# First, view what it looks like.
df_merge.head()

,file,subject,session,task,run,sleep-score,FD-hold,category,arousal_group
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,1,0.959259,eyes_opened,high
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,1,0.974074,eyes_opened,high
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,1,0.974074,eyes_opened,high
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,2,0.981481,eyes_opened,high
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,2,0.977778,eyes_opened,high

In [96]:
df_merge["category"].value_counts() # There should be at least 150 extra "eyes_closed" runs in df_merge after this merge, if successful.

category
eyes_opened    2420
eyes_closed     150
Name: count, dtype: int64

In [97]:
# Make a df that only includes the subject, session, and run that is in the eyes_closed group.
add_subjects_list = df_merge[df_merge.category == "eyes_closed"]

# Drop unneccesary columns.
add_subjects_list = add_subjects_list.drop(columns = ["arousal_group"])

# Re-name variables to match the target df.
add_subjects_list.rename(columns = {"subject": "sub", "session": "ses", "file" : "filename"}, inplace = True)

# Make the values in df_merge sub and ses the same format as df.
add_subjects_list["sub"] = "sub-" + add_subjects_list["sub"].astype(str)
add_subjects_list["ses"] = "ses-" + add_subjects_list["ses"].astype(str)
add_subjects_list["run"] = "run-" + add_subjects_list["run"].astype(str).str.zfill(2)

In [98]:
df.to_csv(r"C:\Users\tempu\Downloads\research\labs\gratton\Arousal-Project\splitting_sample\larger_sample\inet_runs_missing.csv")

# I almost don't care anymore I'm taking this to sheets.

# I found out through sheets that the runs are just missing completely. I need to just add them all manually.

In [99]:
# I use Google Sheets to visualize this better, then I manually edit.
add_subjects_list.to_csv(r"C:\Users\tempu\Downloads\research\labs\gratton\Arousal-Project\splitting_sample\larger_sample\need_to_add.csv")

# CHECK @illinois.edu GOOGLE DRIVE, Arousal > making_csvs > inet_runs.xlsx.

In [100]:
# Accurate df is now loaded.
df = pd.read_csv(r"C:\Users\tempu\Downloads\research\labs\gratton\Arousal-Project\splitting_sample\larger_sample\inet_runs.csv")

# Tracking whether there is a change or not in df length.
PREV_LEN = len(df)

# Drop duplicate runs to be safe.
df = df.drop_duplicates(subset=["sub", "ses", "run"])

# Tracking whether there is a change or not in df length.
CURR_LEN = len(df)

In [101]:
## CHECKS
print("**Change in df length after removing duplicates:** "), print(PREV_LEN - CURR_LEN), print("\n**Value counts of eyes_closed vs eyes_opened runs:**"), print(df["category"].value_counts())

**Change in df length after removing duplicates:**
31

**Value counts of eyes_closed vs eyes_opened runs:**
category
eyes_opened    2438
eyes_closed     155
Name: count, dtype: int64

(None, None, None, None)

In [102]:
# Making sure each var is a string.
df["sub"] = df["sub"].astype(str)
df["ses"] = df["ses"].astype(str)
df["run"] = df["run"].astype(str)

# Re-sort manually appended runs.
df = df.sort_values(by=["sub", "ses", "run"], kind="mergesort")

In [103]:
# INET 165, ses 3, run 3 was appended manually. I want to make sure it appears where it should be
# in the newly sorted df.
df[(df["sub"] == "sub-INET165") & (df["ses"] == "ses-3")].head(4)

# It is, as seen below.

,sub,ses,task,run,category,filename,sleep-score,number_of_TRs,num_tps_retained,FD-hold,fFD_filepath,fFD_filename,tmask_filepath,tmask_filename
2431,sub-INET165,ses-3,task-rest,run-01,eyes_opened,sub-INET165_ses-3_task-rest_run-01_bold.nii.gz,2.0,270,250,0.925926,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-01_desc-fFD.txt,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-01_desc-tmask_...
2432,sub-INET165,ses-3,task-rest,run-02,eyes_opened,sub-INET165_ses-3_task-rest_run-02_bold.nii.gz,3.0,270,244,0.903704,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-02_desc-fFD.txt,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-02_desc-tmask_...
2475,sub-INET165,ses-3,task-rest,run-03,eyes_closed,sub-INET165_ses-3_task-rest_run-03_bold.nii.gz,NaN,270,209,0.774074,NaN,NaN,NaN,NaN
2433,sub-INET165,ses-3,task-rest,run-04,eyes_opened,sub-INET165_ses-3_task-rest_run-04_bold.nii.gz,3.0,270,226,0.837037,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-04_desc-fFD.txt,/gpfs/research/grattonlab/iNetworks/Nifti/deri...,sub-INET165_ses-3_task-rest_run-04_desc-tmask_...

In [ ]:
## I want to add a time column for each run.

TR = 1.1

df["time"] = (df["num_tps_retained"] * TR) / 60

In [105]:
# I want to make two new variables to make updated brain masks.
SAMPLE_BMASK_FPATH = "/projects/illinois/las/psych/cgratton/iNetworks/Nifti/derivatives/preproc_fmriprep-24.1.1/sub-INET001/ses-1/func/sub-INET001_ses-1_task-rest_run-02_space-T1w_desc-brain_mask.nii.gz"
SAMPLE_BMASK_FNAME = "sub-INET001_ses-1_task-rest_run-02_space-T1w_desc-brain_mask.nii.gz"

# For easier string concatenation
ROOT_BMASK_FPATH = "/projects/illinois/las/psych/cgratton/iNetworks/Nifti/derivatives/preproc_fmriprep-24.1.1/"
TASK = "task-rest"
END_BMASK_FNAME = "_space-T1w_desc-brain_mask.nii.gz"

# 1. brainmask_filename
df["bmask_filepath"] = (
    "/projects/illinois/las/psych/cgratton/iNetworks/Nifti/derivatives/preproc_fmriprep-24.1.1/"
    + df["sub"]
    + "/"
    + df["ses"]
    + "/func/"
    + df["sub"]
    + "_"
    + df["ses"]
    + "_"
    + TASK
    + "_"
    + df["run"]
    + END_BMASK_FNAME
)

# 2. brainmask_filepath
df["bmask_filename"] = (
    df["sub"]
    + "_"
    + df["ses"]
    + "_"
    + TASK
    + "_"
    + df["run"]
    + END_BMASK_FNAME
)

# Check if it looks good.
df[["sub", "ses", "run", "bmask_filepath", "bmask_filename"]].head()

,sub,ses,run,bmask_filepath,bmask_filename
0,sub-INET001,ses-1,run-01,/projects/illinois/las/psych/cgratton/iNetwork...,sub-INET001_ses-1_task-rest_run-01_space-T1w_d...
1,sub-INET001,ses-1,run-02,/projects/illinois/las/psych/cgratton/iNetwork...,sub-INET001_ses-1_task-rest_run-02_space-T1w_d...
2,sub-INET001,ses-1,run-03,/projects/illinois/las/psych/cgratton/iNetwork...,sub-INET001_ses-1_task-rest_run-03_space-T1w_d...
3,sub-INET001,ses-1,run-04,/projects/illinois/las/psych/cgratton/iNetwork...,sub-INET001_ses-1_task-rest_run-04_space-T1w_d...
4,sub-INET001,ses-1,run-05,/projects/illinois/las/psych/cgratton/iNetwork...,sub-INET001_ses-1_task-rest_run-05_space-T1w_d...

In [ ]:
## I am going to split the df into low and high arousal

# If eyes are closed OR sleep score is greater than 4 (== 5, 6, or 7), it is low arousal.
df_low = df[((df["category"] == "eyes_closed") | (df["sleep-score"] > 4))]

# If eyes are opened OR sleep score is less than 4 (1, 2, 3), it is high arousal.
df_high = df[(df["category"] == "eyes_opened") | (df["sleep-score"] < 4)]

In [139]:
# Making a summary table for key characteristics of our low arousal runs.

df_low_summary = df_low.groupby("sub").agg({
    "time" : "sum", # total time
    "sleep-score" : "mean", # mean sleep score
    "run" : "count" # number of runs
})

# Only include subjects with more than 5 minutes of data per arousal condition.
df_low_summary = df_low_summary[df_low_summary["time"] > 5]

# Import numpy for level assignment.
import numpy as np

# Add a variable indicating whether they are a precision subject
df_low_summary["level"] = np.where(
    df_low_summary["time"] >= 20,
    "precision",
    "group"
)

# Describe subject-level summary stats
df_low_summary.describe()

            time  sleep-score        run
count  65.000000    59.000000  65.000000
mean   26.528333     4.678249   5.923077
std    14.759920     0.751005   3.341536
min     7.663333     2.000000   2.000000
25%    14.318333     4.854167   3.000000
50%    23.576667     5.000000   5.000000
75%    35.328333     5.000000   8.000000
max    64.955000     5.000000  15.000000

In [ ]:
print("Number of subjects in precision vs group-level analysis:"), print(df_low_summary["level"].value_counts())

# Is it an issue for only 28 subjects to be in the group analysis?

Number of subjects in precision vs group-level analysis:
level
precision    37
group        28
Name: count, dtype: int64

(None, None)

In [150]:
print("Number of low arousal subjects *including* precision subjects:"), print(len(df_low_summary)),

print("\nList of low arousal subjects:"), print(df_low["sub"].unique().tolist())

print("\n---------------------------------------"),

print("\nNumber low arousal subjects *excluding* precision subjects:"), print((df_low_summary["level"] == "group").sum())

print("\n---------------------------------------"),

print("\nNumber of precision subjects:"), print((df_low_summary["level"] == "precision").sum())

print("\nList of precision subjects:"), print((df_low_summary[df_low_summary["level"] == "precision"].index).tolist())

Number of low arousal subjects *including* precision subjects:
65

List of low arousal subjects:
['sub-INET001', 'sub-INET003', 'sub-INET005', 'sub-INET016', 'sub-INET018', 'sub-INET019', 'sub-INET026', 'sub-INET029', 'sub-INET032', 'sub-INET034', 'sub-INET036', 'sub-INET040', 'sub-INET041', 'sub-INET042', 'sub-INET044', 'sub-INET046', 'sub-INET048', 'sub-INET049', 'sub-INET050', 'sub-INET052', 'sub-INET058', 'sub-INET059', 'sub-INET060', 'sub-INET061', 'sub-INET062', 'sub-INET063', 'sub-INET065', 'sub-INET067', 'sub-INET068', 'sub-INET069', 'sub-INET071', 'sub-INET072', 'sub-INET073', 'sub-INET074', 'sub-INET077', 'sub-INET078', 'sub-INET080', 'sub-INET083', 'sub-INET084', 'sub-INET085', 'sub-INET087', 'sub-INET088', 'sub-INET091', 'sub-INET093', 'sub-INET094', 'sub-INET096', 'sub-INET098', 'sub-INET099', 'sub-INET101', 'sub-INET104', 'sub-INET105', 'sub-INET106', 'sub-INET107', 'sub-INET108', 'sub-INET109', 'sub-INET110', 'sub-INET111', 'sub-INET112', 'sub-INET114', 'sub-INET115', 'sub-INET116', 'sub-INET120', 'sub-INET123', 'sub-INET131', 'sub-INET133', 'sub-INET136', 'sub-INET137', 'sub-INET140', 'sub-INET141', 'sub-INET143', 'sub-INET156', 'sub-INET158', 'sub-INET160', 'sub-INET165', 'sub-INET168']

---------------------------------------

Number low arousal subjects *excluding* precision subjects:
28

---------------------------------------

Number of precision subjects:
37

List of precision subjects:
['sub-INET003', 'sub-INET016', 'sub-INET026', 'sub-INET032', 'sub-INET034', 'sub-INET036', 'sub-INET041', 'sub-INET046', 'sub-INET058', 'sub-INET059', 'sub-INET061', 'sub-INET065', 'sub-INET069', 'sub-INET071', 'sub-INET072', 'sub-INET074', 'sub-INET077', 'sub-INET080', 'sub-INET083', 'sub-INET085', 'sub-INET087', 'sub-INET088', 'sub-INET091', 'sub-INET094', 'sub-INET098', 'sub-INET107', 'sub-INET110', 'sub-INET111', 'sub-INET116', 'sub-INET120', 'sub-INET131', 'sub-INET140', 'sub-INET141', 'sub-INET143', 'sub-INET156', 'sub-INET158', 'sub-INET160']

(None, None)

In [ ]:
# Making a summary table for key characteristics of our low arousal runs.

df_high_summary = df_high.groupby("sub").agg({
    "time" : "sum", # total time
    "sleep-score" : "mean", # mean sleep score
    "run" : "count" # number of runs
})

# Add a variable indicating whether they are a precision subject
df_high_summary["precision"] = df_high_summary["time"] > 20

# Describe subject-level summary stats
df_high_summary.describe()

             time  sleep-score        run
count   94.000000    94.000000  94.000000
mean   120.096401     2.706664  26.063830
std     26.852334     0.859531   5.235956
min     49.023333     1.000000  11.000000
25%    101.099167     2.008333  22.000000
50%    122.787500     2.677995  27.000000
75%    141.038333     3.253268  30.000000
max    177.925000     4.500000  39.000000

In [127]:
print("Number of high arousal subjects:"), print(len(df_high_summary)),

print("\nList of high arousal subjects:"), print(df_high["sub"].unique().tolist())

print("\n\nNumber of precision subjects:"), print(df_high_summary["precision"].sum())

print("\nList of precision subjects:"), print((df_high_summary[df_high_summary["precision"] == True].index).tolist())

Number of high arousal subjects:
94

List of high arousal subjects:
['sub-INET001', 'sub-INET002', 'sub-INET003', 'sub-INET005', 'sub-INET006', 'sub-INET010', 'sub-INET016', 'sub-INET018', 'sub-INET019', 'sub-INET026', 'sub-INET027', 'sub-INET029', 'sub-INET030', 'sub-INET032', 'sub-INET033', 'sub-INET034', 'sub-INET035', 'sub-INET036', 'sub-INET038', 'sub-INET039', 'sub-INET040', 'sub-INET041', 'sub-INET042', 'sub-INET044', 'sub-INET045', 'sub-INET046', 'sub-INET047', 'sub-INET048', 'sub-INET049', 'sub-INET050', 'sub-INET051', 'sub-INET052', 'sub-INET055', 'sub-INET056', 'sub-INET057', 'sub-INET058', 'sub-INET059', 'sub-INET060', 'sub-INET061', 'sub-INET062', 'sub-INET063', 'sub-INET065', 'sub-INET067', 'sub-INET068', 'sub-INET069', 'sub-INET070', 'sub-INET071', 'sub-INET072', 'sub-INET073', 'sub-INET074', 'sub-INET075', 'sub-INET077', 'sub-INET078', 'sub-INET080', 'sub-INET083', 'sub-INET084', 'sub-INET085', 'sub-INET086', 'sub-INET087', 'sub-INET088', 'sub-INET091', 'sub-INET093', 'sub-INET094', 'sub-INET095', 'sub-INET096', 'sub-INET099', 'sub-INET101', 'sub-INET103', 'sub-INET104', 'sub-INET106', 'sub-INET107', 'sub-INET108', 'sub-INET109', 'sub-INET110', 'sub-INET111', 'sub-INET112', 'sub-INET114', 'sub-INET115', 'sub-INET116', 'sub-INET120', 'sub-INET123', 'sub-INET131', 'sub-INET133', 'sub-INET136', 'sub-INET137', 'sub-INET140', 'sub-INET141', 'sub-INET143', 'sub-INET156', 'sub-INET158', 'sub-INET159', 'sub-INET160', 'sub-INET165', 'sub-INET168']


Number of precision subjects:
94

List of precision subjects:
['sub-INET001', 'sub-INET002', 'sub-INET003', 'sub-INET005', 'sub-INET006', 'sub-INET010', 'sub-INET016', 'sub-INET018', 'sub-INET019', 'sub-INET026', 'sub-INET027', 'sub-INET029', 'sub-INET030', 'sub-INET032', 'sub-INET033', 'sub-INET034', 'sub-INET035', 'sub-INET036', 'sub-INET038', 'sub-INET039', 'sub-INET040', 'sub-INET041', 'sub-INET042', 'sub-INET044', 'sub-INET045', 'sub-INET046', 'sub-INET047', 'sub-INET048', 'sub-INET049', 'sub-INET050', 'sub-INET051', 'sub-INET052', 'sub-INET055', 'sub-INET056', 'sub-INET057', 'sub-INET058', 'sub-INET059', 'sub-INET060', 'sub-INET061', 'sub-INET062', 'sub-INET063', 'sub-INET065', 'sub-INET067', 'sub-INET068', 'sub-INET069', 'sub-INET070', 'sub-INET071', 'sub-INET072', 'sub-INET073', 'sub-INET074', 'sub-INET075', 'sub-INET077', 'sub-INET078', 'sub-INET080', 'sub-INET083', 'sub-INET084', 'sub-INET085', 'sub-INET086', 'sub-INET087', 'sub-INET088', 'sub-INET091', 'sub-INET093', 'sub-INET094', 'sub-INET095', 'sub-INET096', 'sub-INET099', 'sub-INET101', 'sub-INET103', 'sub-INET104', 'sub-INET106', 'sub-INET107', 'sub-INET108', 'sub-INET109', 'sub-INET110', 'sub-INET111', 'sub-INET112', 'sub-INET114', 'sub-INET115', 'sub-INET116', 'sub-INET120', 'sub-INET123', 'sub-INET131', 'sub-INET133', 'sub-INET136', 'sub-INET137', 'sub-INET140', 'sub-INET141', 'sub-INET143', 'sub-INET156', 'sub-INET158', 'sub-INET159', 'sub-INET160', 'sub-INET165', 'sub-INET168']

(None, None)

In [152]:
28 + (94 - 37)

85

In [ ]:
# Save the csvs.

df_